apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tool-widar
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: test
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: charts/tool-widar
    repoURL: https://github.com/wbstack/charts
    targetRevision: HEAD